apiVersion: pkg.crossplane.io/v1
kind: ProviderConfig
metadata:
  name: config-aws
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-secret
      key: creds