apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: aws-resources
  namespace: argocd
spec:
  source:
    repoURL: 'https://github.com/af-bgo/platform-demo.git'
    targetRevision: main
    path: "gitops/manifests/aws-resources"
  destination:
    namespace: crossplane-system
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
