---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: backstage
  namespace: argocd
spec:
  source:
    chart: backstage
    repoURL: https://backstage.github.io/charts
    targetRevision: 1.3.0
    helm:
      releaseName: backstage
  destination:
    server: https://kubernetes.default.svc
    namespace: backstage
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true