apiVersion: devopstoolkitseries.com/v1alpha1
kind: ClusterClaim
metadata:
  name: istio-eks
spec:
  id: istio-eks
  compositionSelector:
    matchLabels:
      provider: aws-official
      cluster: eks
  parameters:
    nodeSize: small