---
# Source: crossplane/templates/rbac-manager-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rbac-manager
  labels:
    app: crossplane
    chart: crossplane-1.13.2
    release: RELEASE-NAME
    heritage: Helm