apiVersion: cluster.awsblueprints.io/v1alpha1
kind: amazonEks
metadata:
  name: istio-cluster
  namespace: default
spec:
  compositionSelector:
    matchLabels:
      awsblueprints.io/provider: aws
      awsblueprints.io/environment: dev
      awsblueprints.io/subnet-selection: label
      service: eks-cas
  resourceConfig:
    providerConfigName: config-aws
    region: eu-central-1
  parameters:
    # This field tells which role should have admin access to this cluster.
    adminRole: Admin
    version: "1.28"
    endpointPrivateAccess: false
    endpointPublicAccess: true
  managedNodeGroups:
    minSize: 2
  writeConnectionSecretToRef:
    name: istio-eks-cluster