apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-platform-demo
  namespace: argocd
spec:
  source:
    path: gitops/applications
    repoURL: 'https://github.com/af-bgo/platform-demo.git'
    targetRevision: main
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
