# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

#----------------------------------------------------------------------------------
# This example resource creates the following resources
#     1. EKS Cluster with VPC
#     2. EKS Cluster IAM Role
#     3. Attaches EKS Cluster Policies to the IAM Role
#     4. EKS Managed Node group
#     5. IAM Role for EKS Managed Node group
#     6. Attaches EKS Managed Node Policies to the IAM Role
#     7. Update the aws-auth config map to allow admin access (defaults to Admin role)
#     8. Installs Cluster Auto Scaler with proper roles.
#----------------------------------------------------------------------------------
#---
#apiVersion: cluster.awsblueprints.io/v1alpha1
#kind: amazonEks
#metadata:
#  name: istio-cluster
#  namespace: default
#spec:
#  compositionSelector:
#    matchLabels:
#      awsblueprints.io/provider: aws
#      awsblueprints.io/environment: dev
#      awsblueprints.io/subnet-selection: label
#      service: eks-cas
#  resourceConfig:
#    providerConfigName: config-aws
#    region: eu-north-1
#  parameters:
#    # This field tells which role should have admin access to this cluster.
#    adminRole: Admin
#    version: "1.28"
#    endpointPrivateAccess: false
#    endpointPublicAccess: true
#  managedNodeGroups:
#    minSize: 1
#  writeConnectionSecretToRef:
#    name: xplane-eks-cluster-cas

---
apiVersion: eks.appsfactory.de/v1beta1
kind: EKSCluster
metadata:
  name: crossplane-cluster
spec:
  parameters:
    region: eu-north-1
    vpc-name: "EKS-CROSSPLANE-VPC"
    vpc-cidrBlock: "10.10.0.0/20"

    subnet1-public-name: "PUBLIC-WORKER-1"
    subnet1-public-cidrBlock: "10.10.0.0/24"
    subnet1-public-availabilityZone: "us-north-1a"

    subnet2-public-name: "PUBLIC-WORKER-2"
    subnet2-public-cidrBlock: "10.10.1.0/24"
    subnet2-public-availabilityZone: "us-north-1b"

    subnet1-private-name: "PRIVATE-WORKER-1"
    subnet1-private-cidrBlock: "10.10.2.0/24"
    subnet1-private-availabilityZone: "us-north-1a"

    subnet2-private-name: "PRIVATE-WORKER-2"
    subnet2-private-cidrBlock: "10.10.3.0/24"
    subnet2-private-availabilityZone: "us-north-1b"

    cluster-role: arn:aws:iam::XXXX:role/EKS-Cluster-Role
    workernode-role: arn:aws:iam::XXXX:role/EKS-WorkerNode-Role

    k8s-version: "1.28"
    workload-type: "non-gpu"
    workers-size: 2

  compositionRef:
    name: amazon-eks-cluster

  writeConnectionSecretToRef:
    namespace: argocd
    name: crossplane-cluster-connection